### ISSUE TITLE
Add support for pages protected by a username and password

### ISSUE THREAD

**Issue by Rickardo987** [arjunkomath/netdata-ios#1]
Some netdata installations (such as mine [here](https://netdata.rickyg.live/) for example) are protected by a standard username and password. Support could be added for providing login details as additional information. It is already supported by [another netdata client](https://apps.apple.com/us/app/netdata/id1384047269).

**Comment by divThis** [comment]
I'd like to second this request. I have my NetData instance behind Traefik with https and BasicAuth and I'm unable to add my server.

**Comment by arjunkomath** [comment]
I like the idea, I'll add support for basic auth. Sorry for not getting back sooner.

**Comment by arjunkomath** [comment]
@Rickardo987 @divThis Please review this PR #5
