### ISSUE TITLE
How to add parameters to monitor? Pie chart icon just leads to spinning empty pane

### ISSUE THREAD

**Issue by juanejot** [arjunkomath/netdata-ios#10]
Are only the standard System Overview parameters possible to view? I clicked on the pie chart icon to try to add more (upsmon measurements over time that successfully appear in the NetData interface) and the pane that came up just spun, never got to presenting what function it provided. Version 1.5, let me know if you need my hw/sw versions.

**Comment by arjunkomath** [comment]
Please share a screen recording / screenshot of the error with steps to reproduce.

**Comment by juanejot** [comment]
Sure, thank you for responding. Once your NetData app is installed & the server added, I simply tap on the pie chart in the upper right, and a new pane slides over the display and spins endlessly. I assume this pane is meant to find other measurements I could add to your app’s view of my server, but that is not the observed result.

My server is a Raspberry Pi 3 running Ubuntu Server 20.04.1 LTS (no Docker containers), and the only measurements I’ve added (installed to the server before NetData, automatically showed up in NetData’s web interface once NetData was installed) are those provided by Network UPS Tools (NUT). Let me know if the make/model of the UPS, or the (version of the) usbhid-ups driver to read it into NUT are salient.

Jorge Garcia’s NetData iOS app lets me select & view the NUT measurements, so I know they show up on more than the NetData web interface. For continued use, I just don’t prefer his proprietary-sounding terms or the general look of his interface as much as yours… though I hope your interface includes trend lines over selectable amounts of time, in addition to in-the-moment %-of-total rings I see with the default measurements.

See attached screen recording (on iPhone 7, iOS 14.3. Similar result on macOS 11.1 and your Mac App Store app; let me know if you need a screen recording of that too).

Thank you for looking into it!



--
Jon Whatmore
jonnywot@gmail.com

**Comment by juanejot** [comment]
Update to what’s below: about 40 minutes after installing your app & adding my server (during which time I shot the screen recording & wrote what’s below), I again tapped the pie chart icon in your app’s view of my server. When the new pane came up this time (again, ~40 min after app install/server addition), selectable parameters came up, including NUT.

That was a strange while, but glad to see the functionality working as expected. You may consider that issue closed.

I would then move to a feature request: it appears all NUT parameters, like many individual ones of the NetData default parameters you show without further selection, are in-the-moment number values, only. Any plans to chart them over time in the future? That would be useful.

In any event, thank you!

--
Jon Whatmore
+1 (805) 215-6102
jonnywot@gmail.com

**Comment by juanejot** [comment]
It appears that about 40 min after both installation of your iOS app & the addition of my server to it, parameters other than the NetData default ones started loading. We can therefore consider that issue closed; it just took much longer than I expected, but works as expected eventually.

I would like to shift to a feature request though: are you considering showing trend lines in data over time?
Thank you!

**Comment by arjunkomath** [comment]
Yes, I'm considering that.
