### ISSUE TITLE
Informations not showing up

### ISSUE THREAD

**Issue by Nani-o** [arjunkomath/netdata-ios#11]
I had some issue with the widget but somehow made it work with one server.
As soon as I added my Mac mini the widget was off again : 
![image](https://user-images.githubusercontent.com/26149182/112914616-b2bfba80-90fc-11eb-9a92-d1677c686479.jpeg)

I don't know if it's related but network does not show any information for my mini (but does in netdata web interface) : 
![image](https://user-images.githubusercontent.com/26149182/112914665-d4b93d00-90fc-11eb-9515-7a0ea9599722.jpeg)

It's a cool and promising app btw 👍

**Comment by arjunkomath** [comment]
@Nani-o Thanks for reporting the issue, I'll investigate this.

**Comment by arjunkomath** [comment]
@Nani-o Regarding the missing network info, could you check if its shown on Netdata web console? just want to make sure the data is available.

**Comment by Nani-o** [comment]
Yes it is. I thought about adding it with the issue but laziness is strong inside me :

![image](https://user-images.githubusercontent.com/26149182/113185760-24ac1700-9257-11eb-83c0-a24e3be6f792.png)

**Comment by arjunkomath** [comment]
@Nani-o Thanks 👍

**Comment by arjunkomath** [comment]
@Nani-o Are you still facing this issue in v1.8 of the app?
