### ISSUE TITLE
Crashing on M1.

### ISSUE THREAD

**Issue by iMoshi** [arjunkomath/netdata-ios#12]
Awesome app! After installing it from the Mac App Store, I'm able to connect to my netdata installation, but when I select it from "My Servers", app crashes after trying to load it. 

I'm on Big Sur 11.2.3, Apple M1.

**Comment by arjunkomath** [comment]
Hey @iMoshi Sorry that you're having trouble with the app. Could you try removing and adding the server once more?

**Comment by iMoshi** [comment]
> Hey @iMoshi Sorry that you're having trouble with the app. Could you try removing and adding the server once more?

I've actually just realized I can't remove a server. I've right clicked on my server and haven't seen an option to delete it. I've also selected it (which it crashed 2 times already in the process) and clicked Delete from my keyboard, as well as CMD + Delete but none has worked 🥲

**Comment by arjunkomath** [comment]
> > Hey @iMoshi Sorry that you're having trouble with the app. Could you try removing and adding the server once more?
> 
> I've actually just realized I can't remove a server. I've right clicked on my server and haven't seen an option to delete it. I've also selected it (which it crashed 2 times already in the process) and clicked Delete from my keyboard, as well as CMD + Delete but none has worked 🥲

Sorry about that, looks like a bad UX at the moment, I'll address this in the next release.

**Comment by iMoshi** [comment]
> > > Hey @iMoshi Sorry that you're having trouble with the app. Could you try removing and adding the server once more?
> > 
> > 
> > I've actually just realized I can't remove a server. I've right clicked on my server and haven't seen an option to delete it. I've also selected it (which it crashed 2 times already in the process) and clicked Delete from my keyboard, as well as CMD + Delete but none has worked 🥲
> 
> Sorry about that, looks like a bad UX at the moment, I'll address this in the next release.

Thank you, best of luck!

**Comment by arjunkomath** [comment]
@iMoshi A new version has been released, please try and let me know if it's still crashing. 

I've also added the option to delete server using the context menu.
