### ISSUE TITLE
Can‘t add servers on iOS 14.4.2

### ISSUE THREAD

**Issue by marianheinsen** [arjunkomath/netdata-ios#13]
Hi,
clicking the Add button at the My Servers list doesn‘t do anything, so no servers can be added.

**Comment by arjunkomath** [comment]
Hey @marianheinsen, please share the app version and device details so that we can investigate.

**Comment by marianheinsen** [comment]
Hey @arjunkomath 
the device is iPhone Xr with iOS 14.4.2
App version is 1.8 (27)

Thanks

**Comment by tmtns** [comment]
Hello! We're you able to figure out the issue. I am having the same problem.

**Comment by arjunkomath** [comment]
Hey,

I'm able to reproduce the issue, I'll get the fix out very soon. 

Thanks.

**Comment by tmtns** [comment]
No worries. Thank you very much.

**Comment by arjunkomath** [comment]
@marianheinsen  @tmtns  Issue fixed in version 1.8.1 (28) and submitted to App Store.
