### ISSUE TITLE
Netdata Cloud

### ISSUE THREAD

**Issue by Rennerdo30** [arjunkomath/netdata-ios#14]
How can I use this app with Netdata cloud? 
Maybe a button to add a cloud server would be nice.

![image](https://user-images.githubusercontent.com/9086097/120208459-c9ce7600-c22d-11eb-88f6-3be934fee879.png)

**Comment by arjunkomath** [comment]
Hey @Rennerdo30 This app doesn't work with Netdata cloud service, instead you can directly add a server running Netdata agent.
