### ISSUE TITLE
macOS can't add Server

### ISSUE THREAD

**Issue by thefiredragon** [arjunkomath/netdata-ios#15]
I'm unable to add Servers
<img width="306" alt="Bildschirmfoto 2021-05-31 um 23 40 57" src="https://user-images.githubusercontent.com/20144860/120244137-be993b80-c269-11eb-8a29-91b2bcba46ec.png">

**Comment by arjunkomath** [comment]
@thefiredragon From a quick investigation this error seems to be caused by iCloud storage. Could you check if you've free space in iCloud storage?

https://developer.apple.com/documentation/cloudkit/ckerror/2325197-quotaexceeded
