### ISSUE TITLE
show device as offline

### ISSUE THREAD

**Issue by krobipd** [arjunkomath/netdata-ios#18]
hey

I just started with Netdata and your iOS app
I saw that Netdata cloud can show if your device is on- or offline.
but in your app a device is always displayed green and I can select it even it is offline - Netdata cloud knows it is offline.

**Comment by arjunkomath** [comment]
I believe that is a bug, I'll address it soon. Thanks for reporting.

**Comment by arjunkomath** [comment]
@krobipd  Fix is almost ready, will submit to App Store this week.

![Screen Shot 2021-06-29 at 8 20 03 pm](https://user-images.githubusercontent.com/2555067/123781302-6bbdad00-d917-11eb-9254-549ee4884b21.png)
