### ISSUE TITLE
Doesn’t connect over hostname

### ISSUE THREAD

**Issue by agneevX** [arjunkomath/netdata-ios#19]
Hello. 

The app doesn't connect, despite this being a valid URL:

![image](https://user-images.githubusercontent.com/19761269/125643967-a134b96a-3090-41ea-886c-b5fa7d66b6d3.jpeg)

**Comment by arjunkomath** [comment]
@agneevX Few questions:
- Have you tried connecting using the IP instead of the domain name?
- Are you able to view the Netdata server in Safari? If so could you share a screenshot of the same.

**Comment by agneevX** [comment]
> - Have you tried connecting using the IP instead of the domain name?

It's made to be reachable via domain name only. 

> - Are you able to view the Netdata server in Safari? If so could you share a screenshot of the same.

![image](https://user-images.githubusercontent.com/19761269/125737041-4ed5d762-5c79-42bb-bdc7-4814b0c47af4.jpeg)

**Comment by arjunkomath** [comment]
Thanks for sharing that. Could you also confirm that local network access is enabled in privacy settings. 

![image](https://user-images.githubusercontent.com/2555067/125744042-66c6955f-0c8e-4725-8cd8-69a574344c56.jpeg)

**Comment by agneevX** [comment]
It is indeed.

**Comment by arjunkomath** [comment]
Thanks @agneevX I'm not sure why it's failing, I'll investigate and let you know.

**Comment by arjunkomath** [comment]
@agneevX Found the cause of the issue, unfortunately it won't work without HTTPS.

```
Foundation.URLError(_nsError: Error Domain=NSURLErrorDomain Code=-1022 
"The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." 
``` 

In case you're unable to setup HTTPS and cannot use the app, you can request a refund for the app here: https://support.apple.com/HT204084

**Comment by agneevX** [comment]
I use a bunch of other apps including another Netdata client, all over self hosted reverse proxy over HTTP 80.

Surely this is a bug you can fix.

**Comment by agneevX** [comment]
There is a possible solution here if you're up for it.

https://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi

**Comment by arjunkomath** [comment]
@agneevX I'm aware of this fix, but it is not recommended and its highly likely that Apple will reject my app submission, you can read more here: https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads

<img width="755" alt="Screen Shot 2021-07-15 at 10 28 03 pm" src="https://user-images.githubusercontent.com/2555067/125788081-dbbc514f-77c5-454d-97a6-d6f8423c77dc.png">

**Comment by agneevX** [comment]
Well that's very unfortunate. I'll close this issue then.

**Comment by agneevX** [comment]
Can you tell me why this is shown in red, even though its reachable?

![image](https://user-images.githubusercontent.com/19761269/125790020-0207c68f-4b50-4e76-8c42-15a795ae6e1e.png)

**Comment by arjunkomath** [comment]
It is shown as red or in warning state when the Netdata alarms endpoints doesn't return expected data. The app checks alarms to verify the state of the server.

**Comment by agneevX** [comment]
It wasn't this way before the last update.

There are no alarms or any errors with my installation, so this is very peculiar.

**Comment by arjunkomath** [comment]
This feature was added in the last release, but it seems like its not working as intended, I can fix it. 

I'll add the ability to debug such issues in future version of the app. Also, The next version comes with major improvements and it will target iOS 15.

**Comment by agneevX** [comment]
Your target deployment will still remain iOS 14 right?

**Comment by arjunkomath** [comment]
No, iOS 15 offers significant improvements, I'm planning to drop iOS 14 support after a while, probably EOY.
