### ISSUE TITLE
Can’t connect without https (solved)

### ISSUE THREAD

**Issue by FrostyMisa** [arjunkomath/netdata-ios#2]
Hi, your app looks modern and nice, but I have problem. My NetData is on my raspberry pi 4 at home and it's local IP (192.168.0.50:1999) and when I fill this IP in your app it ask me for https connection. Can you make it work for home use like this without https address? Thank you and looking forward for future updates🙃

**Comment by FrostyMisa** [comment]
Problem solved. Added http:// in front of IP and after it's connect 😝. Sorry for waste your time🙃

**Comment by arjunkomath** [comment]
Closing as the issue has been resolved.
