### ISSUE TITLE
Needs access to the Netdata cloud service.

### ISSUE THREAD

**Issue by xxdesmus** [arjunkomath/netdata-ios#20]
It appears the appear can't access the cloud service -- which seems like a major shortcoming. I'd request an iOS app refund if that was an option.

**Comment by arjunkomath** [comment]
yes, this app doesn't work with Netdata cloud, you can request refund here:

https://support.apple.com/HT204084

**Comment by arjunkomath** [comment]
@xxdesmus I've updated the readme to add this information, I'll add the same to app store listing also.

**Comment by xxdesmus** [comment]
Thank you! Sorry if I sounded like I was blaming you. I should have clarified the description could have just been improved. Thanks in any case!
