### ISSUE TITLE
Netdata keeps crashing after pinning apps

### ISSUE THREAD

**Issue by Danrancan** [arjunkomath/netdata-ios#21]
Netdata crashes on ios after pinning more than 3 apps. program closes and have to restart and rescroll. this is a consistent error

**Comment by arjunkomath** [comment]
@Danrancan Thanks for reporting, I'll investigate and get this fixed soon.

**Comment by arjunkomath** [comment]
`v1.11.1` should address the crash, It has been submitted for review.

**Comment by Danrancan** [comment]
This issue should be reopened. My iOS app is still crashing everytime I reopen it. Takes one or two scrolls down before it crashes. Using an iphone 11 with the latest iOS Update.

**Comment by arjunkomath** [comment]
@Danrancan  Does it crash as soon as you open the app or only when there is custom pinned charts?

**Comment by Danrancan** [comment]
> @Danrancan Does it crash as soon as you open the app or only when there is custom pinned charts?

Well its difficult to tell. I DO have pinned charts. The app opens up just fine, but as soon as I start scrolling down, and the pinned charts start to come into view, then the app crashes and dissapears, and I have to reopen it again.

**Comment by arjunkomath** [comment]
> > @Danrancan Does it crash as soon as you open the app or only when there is custom pinned charts?
> 
> Well its difficult to tell. I DO have pinned charts. The app opens up just fine, but as soon as I start scrolling down, and the pinned charts start to come into view, then the app crashes and dissapears, and I have to reopen it again. So I believe it likely has something to do with those pinned charts. Did I miss an issue where this is already open?

Thanks for the information, I'll investigate.
There are no other open issues.

**Comment by michael-sabrnak-swi** [comment]
Hi, I experience similar issue but with raspberry when wmi poller for windows metrics were enabled it started to crash.

**Comment by arjunkomath** [comment]
I've made some fixes based on crash logs I've received, `v1.11.6` should be available this week, please test and let me know.

**Comment by Danrancan** [comment]
> I've made some fixes based on crash logs I've received, `v1.11.6` should be available this week, please test and let me know.

Excellent my good man! I will most certainly test for you. Let me know if there is anything else I can do to assist. I would really like to get this app working flawlessly for everyone. I have an iPhone 11 as well as an iPhone7 I can test this on. So let me know.

**Comment by Danrancan** [comment]
> I've made some fixes based on crash logs I've received, `v1.11.6` should be available this week, please test and let me know.

Any word on v1.11.6? I still don't see it in the app store.

**Comment by arjunkomath** [comment]
I submitted the app for review on Dec 29th and it is still pending. Sadly there isn't much I can do other than wait. 😢 

![image](https://user-images.githubusercontent.com/2555067/148625363-1c560b82-9bec-4bab-b51f-60236be872df.png)

**Comment by arjunkomath** [comment]
Apple approved the build, it should be available for download now. Thanks.

**Comment by arjunkomath** [comment]
😢 Sorry about that, I'll go through the crash logs once more. 

Please provide the following info if possible:
- List of pinned charts
- OS / Arch of the server

Worst case scenario please request refund for the app and I'm sorry for making you go through all this debugging with me.

**Comment by Danrancan** [comment]
> 😢 Sorry about that, I'll go through the crash logs once more. 
> 
> Please provide the following info if possible:
> - List of pinned charts
> - OS / Arch of the server
> 
> Worst case scenario please request refund for the app and I'm sorry for making you go through all this debugging with me. 

Sorry for the delay in reply. I got busy and forgot about this. 

1) Unfortunately, I cannot recreate this issue after reinstalling this app because there is a new issue that I filed where I can no longer Pin charts because the additional charts section is blanked out. Pleease look at my other github issue that I posted to see this.

2) The OS/arch of the server is a Raspberry Pi 4 (aarch64), running Ubuntu server 20.04 LTS.

**Comment by arjunkomath** [comment]
Closing this issue as it's not reproducible.
