### ISSUE TITLE
App crashes caused by non-standard URL

### ISSUE THREAD

**Issue by sambartik** [arjunkomath/netdata-ios#27]
Hello, the app started crashing after going to instance details view as soon as I changed the netdata URL from http://192.168.1.4:19999 to https://192.168.1.4/netdata

**Comment by arjunkomath** [comment]
Thanks for reporting the issue, will investigate and get back to you.

**Comment by arjunkomath** [comment]
@sambartik There was a bug in validation logic and server url was not being properly validated while adding or editing, that has been resolved in [c139b99](https://github.com/arjunkomath/netdata-ios/commit/c139b9962aa9919c64b45e5f19cabe8cb3366f48)

I've tested a server by rewriting Netdata via NGINX and it seem to be working properly.
Could you provide more information about the server and your device; OS, version etc?

**Comment by sambartik** [comment]
Hey, on the server side, I have a nginx reverse proxy that connects to the netdata backend. I am running the app on the latest public iOS version 15.1 on iPhone 11.

**Comment by arjunkomath** [comment]
> Hey, on the server side, I have a nginx reverse proxy that connects to the netdata backend. I am running the app on the latest public iOS version 15.1 on iPhone 11.

Thanks, I've tested similar setup on new version and seem to working. I'll submit it for review today (v1.11.5) it should be out tomorrow.

Once you've installed the new version, try removing and adding the server again and let me know.
Please reopen the issue if the app is still crashing.
