### ISSUE TITLE
Netdata crash if specific node is viewed

### ISSUE THREAD

**Issue by MyKEms** [arjunkomath/netdata-ios#28]
Hi, I have problem with netdata ios cliend. To be specific viewing Raspberry node. It worked but once I enabled monitoring of windows node via native [wmi](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi/) exporter then this specific raspberry node keeps crashing all the time if opened. I can see it will load some of the stats and then crash (like less than a second).

This behavior is same on latest iOS or iPadOS.

**Comment by arjunkomath** [comment]
> Hi, I have problem with netdata ios cliend. To be specific viewing Raspberry node. It worked but once I enabled monitoring of windows node via native [wmi](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi/) exporter then this specific raspberry node keeps crashing all the time if opened. I can see it will load some of the stats and then crash (like less than a second).
> 
> This behavior is same on latest iOS or iPadOS.

Thanks for reporting the issue, hopefully I can investigate this based on crash logs.

I don't have a raspberry pi to reproduce the issue on my end, do you know any public Netdata raspberry pi instances I can use for testing?

**Comment by arjunkomath** [comment]
Based on the crash logs I've made some fixes (https://github.com/arjunkomath/netdata-ios/commit/bd854d0be4e21671fb3e7627d788a9531e23938a) and I'm currently testing it.
The fix should be generally available this week in version `1.11.6`

**Comment by MyKEms** [comment]
Looks latest update fixed the problem. Thanks 👍
