### ISSUE TITLE
Can't add server

### ISSUE THREAD

**Issue by tomkessler** [arjunkomath/netdata-ios#29]
Just purchased the Mac app and when I click the "Add Netdata server" button nothing happens.

**Comment by arjunkomath** [comment]
> Just purchased the Mac app and when I click the "Add Netdata server" button nothing happens.

sorry about that, could you provide the app version (it is at the bottom of settings page) and Mac os version.

**Comment by tomkessler** [comment]
I just upgraded to Mac OS Monterey (prior to installing the Netdata app).  About this Mac reports the version as: 12.1 (21C52).

I installed the Netdata app via the App store and it shows the following in About:   Version 1.11.5 (45).

**Comment by arjunkomath** [comment]
Please try updating to the latest version, I just tested on `12.1` and confirm adding server is working.

<img width="707" alt="CleanShot 2021-12-30 at 14 42 50@2x" src="https://user-images.githubusercontent.com/2555067/147719967-e6553807-4f09-4d0c-aad7-b656d9bdfa82.png">

**Comment by tomkessler** [comment]
Now I get this and I still can't add a server.  
![image](https://user-images.githubusercontent.com/20233788/147763479-ad858f93-8ef7-471c-9941-7fc0fd84c72f.png)

**Comment by arjunkomath** [comment]
> Just purchased the Mac app and when I click the "Add Netdata server" button nothing happens.

iCloud has to be enabled for the app to work as we use it for storing data.

Unfortunately there is not way around it, if you cannot enable iCloud please request refund for the app. You can find instructions here, https://support.apple.com/en-au/HT204084

Sorry for the trouble.

**Comment by tomkessler** [comment]
Requested refund.
