### ISSUE TITLE
Some UI glitches and suggestions

### ISSUE THREAD

**Issue by kobimx** [arjunkomath/netdata-ios#3]
Hey, i've stumbled upon this amazing app for monitoring my Netdata distance but i've noticed some UI glitches
I've uploaded a recording on imgur and i think i found out what the problem is. When you navigate the pages and you go back using a swipe gesture but fail to complete or go back to he staring page the top title text gets duplicated and initialized again

https://imgur.com/NYhvTI9

There are also some other minor glithes, like the cpu usage progress ring doing jumping animation when its initialized and also the free memory graph logic. I think it would be better to set the total free ram value as the combination of "free ram" and "cached ram" charts combined since linux treats cached ram as free ram (see https://www.linuxatemyram.com/)

I'm learning switf ui too so maybe i'll look into the code and make a PR request if i get the time

**Comment by arjunkomath** [comment]
Closing as this issue has been addressed in #4
