### ISSUE TITLE
Charts no longer appear when trying to add more charts in iOS

### ISSUE THREAD

**Issue by Danrancan** [arjunkomath/netdata-ios#31]
Info:
I am using iOS 16.0.2 on an iPhone 11. However, this problem was also occuring before I upgraded iOS when I was using iOS 15.*.*. The server that is running my netdata application off of is a Raspberry Pi 4 (aarch64) LEMP server running Ubuntu 20.04 LTS.

Issue:
The problem is simple. When trying to add more charts to my main netdata screen, no charts actually appear in the charts section. The charts section is just blank even when searching for charts. Essentially, I am stuck using the default charts and only the default charts. Please fix this.

**Comment by arjunkomath** [comment]
@Danrancan Let me investigate the issue, it will be tricky if the issue is specific to raspberry pi servers. If you don't mind, could you share screenshot / video of the bug.

**Comment by arjunkomath** [comment]
Hey @Danrancan Could you share screenshot or video of the issue. Thanks.

**Comment by dominickolbe** [comment]
hey @arjunkomath. first - awesome work! it helped me a lot buildung something with xcode using your source code. (comming from the other dev side haha)

I also noticed that the chart is no longer working, iphone and macbook


https://user-images.githubusercontent.com/6094725/197905130-005908b2-7030-4322-a23f-4efe49c1e13b.mp4

**Comment by arjunkomath** [comment]
@dominickolbe Thank 👍 I can reproduce the issue, I got confused at first, I thought the main screen was empty.

**Comment by Danrancan** [comment]
> Will be fixed in v1.11.7

Excellent news. Let me know if you need anything else from me!
