### ISSUE TITLE
1) Netdata keeps crashing when pinning charts. 2) Not all charts will pin.

### ISSUE THREAD

**Issue by Danrancan** [arjunkomath/netdata-ios#33]
I am running iOS 16.1 on an iPhone 11. The netdata version is 1.11.7 (48). My netdata is running off of a Raspberry Pi 4 running Ubuntu 20.04 Server. 

Issue 1) 
I have tried to pin many charts. However, when looking under the "pinned charts" section in the Netdata iOS app, it doesnt show all of the charts that I actually pinned. 

Issue 2) 
After pinning my charts, I try to go to view my charts in the netdata app, but as soon as i scroll down past the first screen full of charts, the netdata app crashes and I have to reopen it. This has been an isue for almost a year now and I hope I can offer any requested information needed to fix this as soon as possible. Netdata is useless without this working, so I hope there will be a fix soon.

Please let me know if I can do anything to help. 

![image](https://user-images.githubusercontent.com/30222551/198854085-2759132b-c1f2-4d30-80f5-9ddc2b700faf.png)

![image](https://user-images.githubusercontent.com/30222551/198854088-8fd87773-b32b-4903-8bc5-57edaaab8239.png)

https://user-images.githubusercontent.com/30222551/198854390-a9950829-2d38-48ad-9401-94aa7e89ba3a.MOV

**Comment by arjunkomath** [comment]
More fixes are coming soon, seems like iOS 16 (or something else) causes my implementation to break.

**Comment by arjunkomath** [comment]
@Danrancan I've fixed the crash in v1.11.8, it's in AppStore review RN, should be out soon.
