### ISSUE TITLE
Charts appear blank on Raspberry Pi Netdata w iOS 16.3.1

### ISSUE THREAD

**Issue by Danrancan** [arjunkomath/netdata-ios#37]
I am running netdata version 1.11.8 (49) on iOS 16.3.1. My netdata server is a Raspberry Pi 4 running Ubuntu server 20.04. When accessing netdata from any web browser, it works perfectly. However, when using the netdata app on iOS, charts appear to be frozen and blank. Nothing appears. Please see screenshot below and let me know if you need any other information that will help fix this.

![image](https://github.com/arjunkomath/netdata-ios/assets/30222551/930c3b65-b725-4ccf-965f-f9f1cd92cb4a)
![image](https://github.com/arjunkomath/netdata-ios/assets/30222551/83c1a6d4-de16-4895-80d0-4213f828ed77)

**Comment by arjunkomath** [comment]
Can you try updating the app to 1.11.9, I release a hotfix for this bug yesterday. 

A recent change in Netdata API broke the HTTP requests from the app, but I believe it has been resolved.

**Comment by Danrancan** [comment]
> Can you try updating the app to 1.11.9, I release a hotfix for this bug yesterday.
> 
> A recent change in Netdata API broke the HTTP requests from the app, but I believe it has been resolved.
> 
> (Dup of #36)

The update fixed it. Issue resolved. Thanks!
