### ISSUE TITLE
Can’t configure push alerts

### ISSUE THREAD

**Issue by n0lz** [arjunkomath/netdata-ios#58]
Hi,

I tried to configure push notifications as described here: https://github.com/arjunkomath/netdata-ios/blob/main/docs/alert-notifications.md but can’t get it to work. I just won’t receive notifications. I tried to call the API directly and get the message "No device tokens found“. Is this a problem of the API or is the device token something I need to configure somewhere, which I haven’t found yet?

Would be great to get some help :)

Thanks!

**Comment by arjunkomath** [comment]
Hey @n0lz, I'll suggest quitting, reopening the app and toggling alerts once more, it should re-trigger push token fetch. If that doesn't work please email your API key to support@techulus.com so that I can take a look at the data.

**Comment by n0lz** [comment]
Now I get `{"success":true}` as response on the API call, but still no push notification. I'll email you.

**Comment by n0lz** [comment]
The latest update resolved this issue. Thank you :)
