### ISSUE TITLE
Can’t add server

### ISSUE THREAD

**Issue by aetha** [arjunkomath/netdata-ios#9]
Hi, I'm not if I'm missing something here or not, but I don't understand or seem to be able to add servers. I've tried for URL: `http://10.1.1.1:19999/`, `http://10.1.1.1/` `10.1.1.1:19999`, and `10.1.1.1`, and I always get this same error in the screenshot.

![image](https://user-images.githubusercontent.com/3007450/102950366-9d942800-451e-11eb-8240-f065d20d7573.png)

**Comment by arjunkomath** [comment]
@aetha Can you try uninstalling and reinstalling the app, and also make sure the local network permissions are enabled if you're adding a local server.

**Comment by aetha** [comment]
I tried un- and reinstalling, no dice. Looked at the iOS settings page for the app, and can't see any permission for local network access.

![image](https://user-images.githubusercontent.com/3007450/102955990-56606400-452b-11eb-8a90-d052f6297614.png)

Currently running iPadOS 14.2 btw, (about to update to 14.3).

**Comment by arjunkomath** [comment]
Looks like a bug, I had a similar report couple of days back. I'll investigate and let you know.

**Comment by aetha** [comment]
Cool, thanks! 😊

**Comment by arjunkomath** [comment]
Fixed in 1.6 (20)
